[package]
name = "keon"
version = "0.2.0"
edition = "2021"
rust-version = "1.74.0"
authors = ["K--Aethiax"]

description = "A human readable object notation that syntactic similar to Rust and fully supports Serde's data model."

documentation = "https://docs.rs/keon"
repository = "https://github.com/eternal-io/keon"
license = "MIT OR Apache-2.0"
readme = "CRATES.IO-README.md"

keywords = ["serde", "serialization", "object-notation", "format", "parser"]
categories = ["encoding"]


[features]
default = ["std", "alloc", "dep:ecow"]
std = [
    "alloc",
    "serde/std",
    "memchr/std",
    "simdutf8/std",
    "data-encoding/std",
    "lexical-parse-float/std",
    "lexical-parse-integer/std",
    "lexical-write-integer/std",
    "ecow/std",
]
alloc = [
    "serde/alloc",
    "memchr/alloc",
    "data-encoding/alloc",
]
ecow = ["alloc"]


[dependencies]
zmij = "1.0.23"
bitflags = "2.13.1"
unicode-ident = "1.0.24"
serde = { version = "1.0.229", default-features = false }
either = { version = "1.17.0", default-features = false }
memchr = { version = "2.8.3", default-features = false }
simdutf8 = { version = "0.1.5", default-features = false }
data-encoding = { version = "2.11.0", default-features = false }
lexical-util = { version = "1.0.7", default-features = false }
lexical-parse-float = { version = "1.0.6", default-features = false, features = ["format"] }
lexical-parse-integer = { version = "1.0.6", default-features = false, features = ["format", "power-of-two"] }
lexical-write-integer = { version = "1.0.6", default-features = false }
ecow = { version = "0.3.0", default-features = false, optional = true }


[dev-dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_bytes = "0.11.19"
