[package]
name = "keon"
version = "0.2.0"
edition = "2021"
rust-version = "1.74.0"
authors = ["K--Aethiax"]

description = "A human readable object notation that syntactic similar to Rust and fully supports Serde's data model."

documentation = "https://docs.rs/keon"
repository = "https://github.com/eternal-io/keon"
license = "MIT OR Apache-2.0"
readme = "CRATES.IO-README.md"

keywords = ["serde", "serialization", "object-notation", "format", "parser"]
categories = ["encoding"]


[features]
default = ["std", "alloc"]
std = []
alloc = []


[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
either = "1.17.0"
memchr = "2.8.3"
simdutf8 = "0.1.5"
lexical-core = { version = "1.0.6", features = ["format", "power-of-two"] }
data-encoding = "2.11.0"
unicode-ident = "1.0.24"


[dev-dependencies]
serde_json = "1.0.151"
serde_bytes = "0.11.19"
